web/web/forms/users.py
from flask_wtf import FlaskForm
from wtforms import fields, validators

class LoginForm(FlaskForm):
    username = fields.StringField(
        "Username", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    password = fields.PasswordField(
        "Password", validators=[validators.DataRequired(), validators.Length(min=3)]
    )


class RegistrationForm(FlaskForm):
    username = fields.StringField(
        "Username", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    email = fields.StringField(
        "Email",
        validators=[
            validators.DataRequired(),
            validators.Length(min=3),
            validators.Email(),
        ],
    )
    password = fields.PasswordField(
        "Password", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    password_confirm = fields.PasswordField(
        "Password Confirm",
        validators=[
            validators.DataRequired(),
            validators.Length(min=3),
            validators.EqualTo("password", message="Passwords must match"),
        ],
    )

web/web/views/users.py
from flask import Flask, render_template, redirect, url_for, request, Blueprint
from flask_login import login_required, login_user, logout_user


from . import bcrypt

from .. import forms
from .. import models

bp = Blueprint("users", __name__, url_prefix="/users")


@bp.route("/login", methods=["GET", "POST"])
def login():
    form = forms.LoginForm()

    if not form.validate_on_submit():
        return render_template("users/login.html.j2", form=form)

    user = models.User.query.filter_by(username=form.username.data).first()
    if not user:
        return redirect(url_for("users.login", error="user not found"))

    is_valid = bcrypt.check_password_hash(user.password, form.password.data)
    if not is_valid:
        return redirect(url_for("users.login", error="user or password miss match"))

    login_user(user)
    return redirect(url_for("site.index"))


@bp.route("/register", methods=["GET", "POST"])
def register():
    form = forms.RegistrationForm()
    if not form.validate_on_submit():
        return render_template("/users/register.html.j2", form=form)

    user = models.User()
    form.populate_obj(obj=user)
    user.password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")

    models.db.session.add(user)
    models.db.session.commit()
    return redirect(url_for("users.login"))


@bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("site.index"))


@bp.route("/me")
def me():
    return "Hello World"

web/web/templates/users/login.html.j2
{% extends "base.html.j2" %}

{% block content %}
<h1>Login</h1>
{% if request.args.get('error') %}
<div class="alert alert-danger" role="alert">
  {{ request.args.get('error') }}
</div>
{% endif %}
<form method="POST">
  {{ form.hidden_tag() }}
  <div class="mb-3">
    {{ form.username.label(class_="form-label") }}
    {{ form.username(class_="form-control") }}
  </div>
  <div class="mb-3">
    {{ form.password.label(class_="form-label") }}
    {{ form.password(class_="form-control") }}
  </div>


  <button type="submit" class="btn btn-primary">Login</button>
  <a href="{{ url_for('users.register') }}" class="btn btn-primary">Register</a>
</form>

{% endblock %}

web/web/templates/users/register.html.j2
{% extends "base.html.j2" %}

{% block content %}
<h1>Register</h1>
{% if request.args.get('error') or form.errors %}
<div class="alert alert-danger" role="alert">
  {{ request.args.get('error') }}
  <ul>
    {% for k, v in form.errors.items() %}
    <li>{{ k }}: {{ v }}</li>
    {% endfor %}
  </ul>
</div>
{% endif %}
<form method="POST">
  {{ form.hidden_tag() }}
  <div class="mb-3">
    {{ form.username.label(class_="form-label") }}
    {{ form.username(class_="form-control") }}
  </div>
  <div class="mb-3">
    {{ form.email.label(class_="form-label") }}
    {{ form.email(class_="form-control") }}
  </div>

  <div class="mb-3">
    {{ form.password.label(class_="form-label") }}
    {{ form.password(class_="form-control") }}
  </div>

  <div class="mb-3">
    {{ form.password_confirm.label(class_="form-label") }}
    {{ form.password_confirm(class_="form-control") }}
  </div>

  <button type="submit" class="btn btn-primary">Register</button>
  <a href="{{ url_for('users.login') }}" class="btn btn-primary">Login</a>
</form>

{% endblock %}