web/web/views/groups.py
from flask import Flask, render_template, redirect, url_for, request, Blueprint
from flask_login import login_required, current_user
import datetime

from . import bcrypt

from .. import forms
from .. import models

bp = Blueprint("groups", __name__, url_prefix="/groups")


@bp.route("/create", methods=["GET", "POST"], defaults=dict(group_id=None))
@bp.route("/<group_id>/edit", methods=["GET", "POST"])
@login_required
def create_or_edit(group_id):
    group = None
    if group_id:
        group = models.User.query.filter_by(id=group_id).first()

    form = forms.GroupForm()
    if group and request.method == "GET":
        form = forms.GroupForm(obj=group)

    if not form.validate_on_submit():
        return render_template("/groups/create_or_edit.html.j2", form=form)

    if not group:
        group = models.Group()
        group.created_by = current_user
        group.created_date = datetime.datetime.now()

    form.populate_obj(obj=group)
    group.ip_address = request.environ.get("REMOTE_ADDR", "")

    models.db.session.add(group)
    models.db.session.commit()
    return redirect(url_for("groups.view", group_id=group.id))


@bp.route("/<group_id>")
@login_required
def view(group_id):
    form = forms.MessageForm()
    group = models.Group.query.filter_by(id=group_id).first()
    return render_template("/groups/view.html.j2", form=form, group=group)


@bp.route("/<group_id>/write", methods=["POST", "GET"])
@login_required
def write(group_id):
    form = forms.MessageForm()

    group = models.Group.query.filter_by(id=group_id).first()

    if not form.validate_on_submit():
        return render_template("groups/view.html.j2", form=form, groups=group)

    # create model

    message = models.Message()
    message.message = request.form.get("message", "No message")
    message.created_date = datetime.datetime.now()
    message.ip_address = request.environ["REMOTE_ADDR"]
    message.post_by = current_user
    message.group = group
    # save model
    models.db.session.add(message)
    models.db.session.commit()

    return redirect(url_for("groups.view", group_id=group_id))

web/web/views/posts.py
from flask import Flask, render_template, redirect, url_for, request, Blueprint
from flask_login import login_required, current_user
import datetime

from .. import forms
from .. import models

bp = Blueprint("posts", __name__, url_prefix="/posts")


@bp.route("/post_by_user/<user_id>")
@login_required
def post_by(user_id):
    user = models.User.query.filter_by(id=user_id).first()
    messages = models.db.session.execute(
        models.db.select(models.Message).filter_by(post_by_id=user.id)
    ).scalars()
    return render_template("posts/post_by.html.j2", messages=messages, user=user)

web/web/templates/groups/create_or_edit.html.j2
{% extends "base.html.j2" %}

{% block content %}
<h1>Create Group</h1>
<form method="POST">
  {{ form.hidden_tag() }}
  <div class="mb-3">
    {{ form.name.label(class_="form-label") }}
    {{ form.name(class_="form-control") }}
    <div id="name-help" class="form-text">Write the group name</div>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

web/web/templates/groups/view.html.j2
{% extends "base.html.j2" %}

{% block content %}
<h1> {{ group.name }}</h1>
<div class="row border border-primary" style="padding:10px;">
  <div class="col">
    create by {{ group.created_by.username }} <br />
    create date {{ group.created_date }}
  </div>
  <div class="col text-end">
    <a href="{{ url_for('groups.create_or_edit') }}" class="btn btn-primary">Create Group</a>
  </div>
</div>
<div class="row" style="padding-top:1em;">
  <h3>Write the message</h3>
  <form method="POST" action="{{ url_for('groups.write', group_id=group.id) }}">
    {{ form.hidden_tag() }}
    <div class="mb-3">
      {# <label for="message" class="form-label">Message</label>
      <input type="text" name="message" class="form-control" id="message" aria-describedby="message-help"> #}
      {{ form.message.label(class_="form-label") }}
      {{ form.message(class_="form-control") }}
      <div id="meaage-help" class="form-text">Write the story</div>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

</div>
<div class="row row-cols-3" style="padding-top:1em;">
  {% for message in group.messages %}
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ message.message|screen_out_word }}</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary"><i class="bi bi-clock"></i> {{ message.created_date }}</h6>
        <p class="card-text">ip: {{ message.ip_address }} user: <a
            href="{{ url_for('posts.post_by', user_id=message.post_by.id) }}">{{ message.post_by.username }}</a></p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>



{% endblock %}