web/web/views/site.py
from flask import Flask, render_template, redirect, url_for, request, Blueprint
from flask_login import login_required

from .. import models

bp = Blueprint("site", __name__)


@bp.route("/")
@login_required
def index():
    groups = models.db.session.execute(models.db.select(models.Group)).scalars()

    return render_template("site/index.html.j2", groups=groups)

web/web/views/users.py
from flask import Flask, render_template, redirect, url_for, request, Blueprint
from flask_login import login_required, login_user, logout_user


from . import bcrypt

from .. import forms
from .. import models

bp = Blueprint("users", __name__, url_prefix="/users")


@bp.route("/login", methods=["GET", "POST"])
def login():
    form = forms.LoginForm()

    if not form.validate_on_submit():
        return render_template("users/login.html.j2", form=form)

    user = models.User.query.filter_by(username=form.username.data).first()
    if not user:
        return redirect(url_for("users.login", error="user not found"))

    is_valid = bcrypt.check_password_hash(user.password, form.password.data)
    if not is_valid:
        return redirect(url_for("users.login", error="user or password miss match"))

    login_user(user)
    return redirect(url_for("site.index"))


@bp.route("/register", methods=["GET", "POST"])
def register():
    form = forms.RegistrationForm()
    if not form.validate_on_submit():
        return render_template("/users/register.html.j2", form=form)

    user = models.User()
    form.populate_obj(obj=user)
    user.password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")

    models.db.session.add(user)
    models.db.session.commit()
    return redirect(url_for("users.login"))


@bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("site.index"))


@bp.route("/me")
def me():
    return "Hello World"

web/web/templates/base.html.j2
<!DOCTYPE html>
<html>

<head>

    <title>{% block title %}Hello AIE{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="{{ url_for('static', filename='images/PSU Logo.png') }}" height="30px" />
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('site.index') }}">Home</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('users.logout') }}" class="nav-link active">Logout</a>
                    </li>
                    {% endif %}
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container">
        {%block content %}{% endblock %}
    </div>


</body>

</html>